import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '@/theme';

export const styles = StyleSheet.create({
  sheet: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.md,
    gap: 14,
  },
  userHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  userHeaderMain: {
    flex: 1,
    minWidth: 0,
  },
  mutualRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.md,
    alignSelf: 'flex-start',
  },
  mutualAvatars: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  mutualAvatarWrap: {
    borderWidth: 2,
    borderColor: colors.surface,
    borderRadius: 12,
  },
  mutualAvatarOverlap: {
    marginLeft: -8,
  },
  mutualAvatar: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.surfaceAlt,
  },
  mutualAvatarPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  mutualInitial: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: '700',
  },
  mutualText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '600',
  },
  overflowBtn: {
    width: 40,
    height: 40,
    borderRadius: radius.md,
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  overflowBtnText: {
    color: colors.textSecondary,
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 1,
  },
  fetchErrorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    alignSelf: 'flex-start',
  },
  fetchErrorText: {
    color: colors.textMuted,
    fontSize: 13,
  },
  fetchErrorRetry: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '700',
  },
  sectionLabel: {
    color: colors.textFaint,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  trustBlock: { gap: 6 },
  trustHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  trustText: { color: colors.textMuted, fontSize: 12, fontWeight: '600' },
  trustBadges: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  trustChip: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  trustChipText: { color: colors.textSecondary, fontSize: 12, fontWeight: '600' },
  trustChipStrong: {
    backgroundColor: colors.primary,
  },
  trustChipStrongText: { color: colors.onPrimary, fontSize: 12, fontWeight: '700' },
  trustEmpty: { color: colors.textFaint, fontSize: 12 },
  statsBlock: { gap: 6 },
  statsRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8 },
  statPill: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statPillValue: { color: colors.textPrimary, fontSize: 12, fontWeight: '700' },
  achievementIcons: { flexDirection: 'row', gap: 4 },
  achievementIcon: { fontSize: 16 },
  bio: { color: colors.textSecondary, fontSize: 14, lineHeight: 20 },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  primaryBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  waveBtn: { backgroundColor: colors.primary },
  messageBtn: { backgroundColor: colors.action },
  btnDisabled: { opacity: 0.5 },
  primaryBtnText: { color: colors.onPrimary, fontWeight: '700', fontSize: 14 },
  profileBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.bg,
  },
  profileBtnText: { color: colors.textPrimary, fontWeight: '600', fontSize: 14 },
  kindHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  kindDot: { width: 8, height: 8, borderRadius: 4 },
  kindDotEvent: { backgroundColor: colors.entityEvent },
  kindDotListing: { backgroundColor: colors.entityListing },
  kindDotWanted: { backgroundColor: colors.entityWanted },
  kindLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  kindLabelWanted: { color: colors.entityWanted },
  entityTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
  },
  metaRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 6 },
  metaText: { color: colors.textSecondary, fontSize: 13 },
  metaDot: { color: colors.textFaint },
  priceText: { color: colors.textPrimary, fontSize: 15, fontWeight: '700' },
  entityPrimaryBtn: { alignSelf: 'stretch', marginTop: 4 },
  listingPrimaryBtn: {
    backgroundColor: colors.action,
  },
  entityCover: {
    width: '100%',
    height: 140,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceAlt,
  },
  listingTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  listingThumb: {
    width: 72,
    height: 72,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceAlt,
  },
  listingThumbPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  listingThumbPlaceholderText: {
    fontSize: 28,
  },
  listingTopText: {
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  entityActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  entityActionPrimary: {
    flexGrow: 1,
    alignSelf: 'auto',
  },
  entityActionSecondary: {
    flexGrow: 0,
  },
});
